name: invipen
channels:
  - defaults
dependencies:
  - attrs=19.3.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.5=py_0
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py37_0
  - dbus=1.13.14=h517e14e_0
  - decorator=4.4.2=py_0
  - expat=2.2.6=h0a44026_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.63.1=hd977a24_0
  - icu=58.2=h0a44026_3
  - importlib_metadata=1.7.0=0
  - intel-openmp=2019.4=233
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jinja2=2.11.2=py_0
  - joblib=0.15.1=py_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.2.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py37_0
  - libcxx=10.0.0=1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h0a44026_6
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - llvm-openmp=10.0.0=h28b9765_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - nbconvert=5.6.1=py37_0
  - ncurses=6.2=h0a44026_1
  - notebook=6.0.3=py37_0
  - numpy-base=1.18.1=py37h3304bdc_1
  - openssl=1.1.1g=h1de35cc_0
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.7.0=py_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.8.0=py37_0
  - pip=20.0.2=py37_3
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - pygments=2.6.1=py_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h655552a_2
  - pyrsistent=0.16.0=py37h1de35cc_0
  - python=3.7.7=hc70fcce_0_cpython
  - python-dateutil=2.8.1=py_0
  - qt=5.9.7=h468cd18_1
  - qtpy=1.9.0=py_0
  - readline=8.0=h1de35cc_0
  - scikit-learn=0.22.1=py37h27c97d8_0
  - scipy=1.4.1=py37h9fa6033_0
  - setuptools=46.0.0=py37_0
  - sip=4.19.8=py37h0a44026_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h5c1f38d_1
  - testpath=0.4.4=py_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.4=py37h1de35cc_1
  - traitlets=4.3.3=py37_0
  - wheel=0.34.2=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.2=hb1e8313_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - absl-py==0.9.0
    - appnope==0.1.0
    - astor==0.8.1
    - astunparse==1.6.3
    - backcall==0.1.0
    - cachetools==4.1.0
    - chardet==3.0.4
    - cycler==0.10.0
    - cython==0.29.17
    - defusedxml==0.6.0
    - entrypoints==0.3
    - gast==0.3.3
    - google-auth==1.14.3
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.29.0
    - h5py==2.10.0
    - idna==2.9
    - importlib-metadata==1.6.0
    - ipykernel==5.2.1
    - ipython==7.14.0
    - ipython-genutils==0.2.0
    - jedi==0.17.0
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - lxml==4.5.0
    - markdown==3.2.2
    - matplotlib==3.2.1
    - nbformat==5.0.6
    - numpy==1.18.4
    - oauthlib==3.1.0
    - opt-einsum==3.2.1
    - packaging==20.3
    - pandas==1.0.3
    - pickleshare==0.7.5
    - pillow==7.1.2
    - prometheus-client==0.7.1
    - protobuf==3.12.0
    - ptyprocess==0.6.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.0
    - pyinquirer==1.0.3
    - pyqt5==5.13.2
    - pyqt5-sip==12.7.2
    - pytz==2020.1
    - pyyaml==5.3.1
    - pyzmq==19.0.1
    - qtconsole==4.7.4
    - regex==2020.6.8
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - send2trash==1.5.0
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorflow==2.2.0
    - tensorflow-cpu==2.2.0
    - tensorflow-estimator==2.2.0
    - tensorflow-hub==0.7.0
    - tensorflowjs==2.0.1.post1
    - termcolor==1.1.0
    - terminado==0.8.3
    - urllib3==1.25.9
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - wrapt==1.12.1
prefix: /Users/nipasuma/opt/miniconda3/envs/invipen

